#!/usr/bin/env python3
"""Fetch published Judge.me reviews and write a slim reviews.json the theme reads
via jsDelivr. Runs server-side in GitHub Actions (no browser CORS limits)."""
import os, json, datetime, urllib.request

TOKEN = os.environ["JUDGEME_TOKEN"]                 # Judge.me PUBLIC token (repo secret)
SHOP  = os.environ.get("SHOP_DOMAIN", "d0xj1z-zj.myshopify.com")
API   = ("https://judge.me/api/v1/reviews.json"
         "?api_token=%s&shop_domain=%s&per_page=100&published=true") % (TOKEN, SHOP)

req = urllib.request.Request(API, headers={"User-Agent": "ubratech-reviews-bot"})
with urllib.request.urlopen(req, timeout=30) as r:
    data = json.load(r)

raw = data.get("reviews", [])
out = []
for v in raw:
    body = (v.get("body") or "").strip()
    rating = v.get("rating")
    if not body or (rating is not None and rating < 4):
        continue
    rv = v.get("reviewer") or {}
    name = rv.get("name") or rv.get("display_name") or "Customer"
    out.append({
        "name": name,
        "rating": rating or 5,
        "created_at": (v.get("created_at") or "")[:10],
        "body": body,
    })

# newest first; the theme shows the top 3
out.sort(key=lambda x: x["created_at"], reverse=True)
out = out[:6]
avg = round(sum(r["rating"] for r in out) / len(out), 1) if out else 5.0

payload = {
    "updated": datetime.datetime.utcnow().strftime("%Y-%m-%d"),
    "average": avg,
    "count": len([v for v in raw if (v.get("rating") or 0) >= 4]),
    "note": "Auto-generated by publish-reviews.yml from the Judge.me API.",
    "reviews": out,
}
with open("reviews.json", "w", encoding="utf-8") as f:
    json.dump(payload, f, ensure_ascii=False, indent=2)
print("Wrote reviews.json: %d shown, avg %s" % (len(out), avg))
